### ISSUE TITLE
website cert error

### ISSUE THREAD

**Issue by ungoldman** [feross/whiteboard#6]
## steps to reproduce
- GOTO> https://whiteboard.webtorrent.io/
- EXPECTED> a website
- ACTUAL> `NET::ERR_CERT_COMMON_NAME_INVALID`
- NOTES> http redirects to https. guessing cert doesn't cover `whiteboard` subdomain.

**Comment by feross** [comment]
Yeah, the site redirects because of HSTS. https://*.webtorrent.io is preloaded into all browsers as "always to be requested over HTTPS". https://hstspreload.appspot.com/

The solution is to get a better cert (like a wildcard one), or to host the app in a different place, like webtorrent.io/demos/whiteboard

**Comment by jeremyll** [comment]
https://letsencrypt.org/

**Comment by feross** [comment]
@jeremyll I don't think let's encrypt supports wildcard certificates yet

**Comment by jhermsmeier** [comment]
@feross it doesn't at the moment (afaik), the workaround there is to just get one cert per subdomain, which is pretty hassle-free
